### PR TITLE
Optimize major bottleneck in the NB Pulsar driver when running a consumer workload

### PR DESCRIPTION
**Pull request by lhotari**
We performed some profiling with Java Flight Recorder for a Nosqlbench Pulsar workload since the CPU consumption and GC collection time was high. 

Here are some screenshots of the Flamegraph:

image

image

This PR targets this bottleneck.

Caches should be using `computeIfAbsent` to prevent races. It was previously used in one location in `PulsarSpace` class. This PR changes also other code locations in `PulsarSpace` to use it for lookups to `producers`, `consumers` and `readers` caches. The Apache Commons Lang3 Pair and Triple classes are used as cache keys to reduce the number of generated String objects. The previous cache key solution was inefficient.

Here's an example of an inefficient method:
```
    public static boolean isValidSubscriptionType(String item) {
        return Arrays.stream(SUBSCRIPTION_TYPE.values()).anyMatch(t -> t.label.equals(item));
    }
```

It's recommended to create a static field in the enum to optimize such mappings
```java
    public enum SUBSCRIPTION_TYPE {
        Exclusive("Exclusive"),
        Failover("Failover"),
        Shared("Shared"),
        Key_Shared("Key_Shared");

        public final String label;

        SUBSCRIPTION_TYPE(String label) {
            this.label = label;
        }

        private static final Set<String> LABELS = Stream.of(values()).map(v -> v.label)
            .collect(Collectors.toUnmodifiableSet());

        public static boolean isValidLabel(String label) {
            return LABELS.contains(label);
        }
    }

    public static boolean isValidSubscriptionType(String item) {
        return SUBSCRIPTION_TYPE.isValidLabel(item);
    }
```

The same approach works for more complex solutions, for example

```java
    public enum SEQ_ERROR_SIMU_TYPE {
        OutOfOrder("out_of_order"),
        MsgLoss("msg_loss"),
        MsgDup("msg_dup");

        public final String label;

        SEQ_ERROR_SIMU_TYPE(String label) {
            this.label = label;
        }

        private static final Map<String, SEQ_ERROR_SIMU_TYPE> MAPPING = Stream.of(values())
            .flatMap(simuType ->
                Stream.of(simuType.label,
                        simuType.label.toLowerCase(),
                        simuType.label.toUpperCase(),
                        simuType.name(),
                        simuType.name().toLowerCase(),
                        simuType.name().toUpperCase())
                    .distinct().map(key -> Map.entry(key, simuType)))
            .collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));

        public static Optional<SEQ_ERROR_SIMU_TYPE> parseSimuType(String simuTypeString) {
            return Optional.ofNullable(MAPPING.get(simuTypeString.trim()));
        }
    }
```

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
great stuff

**Review by nicoloboschi — APPROVED** [review]

**Review by jshook — APPROVED** [review]
LGTM

**Comment by jshook** [comment]
@lhotari There are failing tests on this PR, can you investigate?

**Review by jshook — CHANGES_REQUESTED** [review]
Failing tests on branch

**Comment by lhotari** [comment]
> @lhotari There are failing tests on this PR, can you investigate?

@jshook Problem fixed with 21b28bd.

**Review by jshook — APPROVED** [review]
LGTM, merging up

**Comment by yabinmeng** [comment]
Shouldn't we fix this and merge in the main branch?

**Pull request merged**
