### PR TITLE
Adding filters for data api driver adapter

### PR DESCRIPTION
**Pull request by sahankj2000**
Adding the missing filters as per issue: #1973

### CODE REVIEW

**Comment by sahan-ctds** [comment]
@jshook, @MarkWolters `not` filter has not been added in yet!!!. The `not` filter takes in one other filter as an argument so feels like it should be a conjunction, but then there will be cases like `not condition1 or not condition2` where it should go under other conjunctions. Any proposals for this?
Also **IIUC** we cant have nested conditions for this adapter yet for example: `$and($or(condition1, condition2), $or(condition3, condition4))`. Do we want to plan to cover for such cases?

**Comment by sahankj2000** [comment]
Hi @jshook @MarkWolters, here`not` filter has not been added in yet!!!. The `not` filter takes in one other filter as an argument so feels like it should be a conjunction, but then there will be cases like `not condition1 or not condition2` where it should go under other conjunctions. Any proposals for this?
Also **IIUC** we cant have nested conditions for this adapter yet for example: `$and($or(condition1, condition2), $or(condition3, condition4))`. Do we want to plan to cover for such cases?

**Review by MarkWolters — APPROVED** [review]
I think this looks good, expands the filtering type capabilities quite a bit. It would be good to see a unit test case to verify the functionality but I don't see anything that strikes me as incorrect.

**Review by jshook — APPROVED** [review]
LGTM

**Pull request merged**
